export type FinancialCategoryType = 'INCOME' | 'EXPENSE'
export type FinancialTransactionType = 'INCOME' | 'EXPENSE'
export type FinancialTransactionSortField = 'dueDate' | 'netAmount' | 'status' | 'description'
export type FinancialTransactionSortDirection = 'asc' | 'desc'
export type FinancialAccountType = 'CHECKING' | 'SAVINGS' | 'PAYMENT'
export type FinancialReconciliationStatus = 'PENDING' | 'IN_PROGRESS' | 'RECONCILED' | 'DISCREPANCY'

export type FinancialTransactionStatus =
  | 'PENDING'
  | 'PAID'
  | 'OVERDUE'
  | 'CANCELLED'
  | 'REFUNDED'
  | 'PARTIALLY_PAID'

export interface FinancialCategory {
  id: string
  tenantId: string
  name: string
  description?: string | null
  type: FinancialCategoryType
  parentCategoryId?: string | null
  isActive: boolean
  isSystemDefault: boolean
  createdBy: string
  updatedBy?: string | null
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
  parent?: {
    id: string
    name: string
    type: FinancialCategoryType
  } | null
}

export interface FinancialTransaction {
  id: string
  tenantId: string
  type: FinancialTransactionType
  categoryId: string
  residentId?: string | null
  residentContractId?: string | null
  amount: string | number
  discountAmount: string | number
  lateFeeAmount: string | number
  netAmount: string | number
  currency: string
  issueDate: string
  dueDate: string
  competenceMonth: string
  paymentDate?: string | null
  paymentMethodId?: string | null
  bankAccountId?: string | null
  status: FinancialTransactionStatus
  description: string
  notes?: string | null
  isAutoGenerated: boolean
  generationSource?: string | null
  isRecurring: boolean
  recurrenceFrequency?: string | null
  confirmedBy?: string | null
  createdBy: string
  updatedBy?: string | null
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
  category: {
    id: string
    name: string
    type: FinancialCategoryType
  }
  paymentMethod?: {
    id: string
    name: string
    code: string
  } | null
  bankAccount?: {
    id: string
    bankName: string
    accountName: string
  } | null
}

export interface FinancialPagination {
  page: number
  limit: number
  total: number
  totalPages: number
}

export interface FinancialPaymentMethod {
  id: string
  tenantId?: string
  name: string
  code: string
  description?: string | null
  requiresManualConfirmation?: boolean
  allowsInstallments?: boolean
  maxInstallments?: number
  isActive: boolean
  createdAt?: string
  updatedAt?: string
  deletedAt?: string | null
}

export interface FinancialBankAccount {
  id: string
  tenantId?: string
  bankCode?: string
  accountName: string
  bankName: string
  branch?: string
  accountNumber?: string
  accountType: FinancialAccountType
  pixKey?: string | null
  pixKeyType?: string | null
  currentBalance?: string | number
  isDefault?: boolean
  isActive: boolean
  createdBy?: string
  updatedBy?: string | null
  createdAt?: string
  updatedAt?: string
  deletedAt?: string | null
}

export interface FinancialReconciliationItem {
  id: string
  reconciliationId: string
  transactionId: string
  isReconciled: boolean
  reconciliationNotes?: string | null
  reconciledAt?: string | null
  reconciledBy?: string | null
  transaction: {
    id: string
    description: string
    type: FinancialTransactionType
    netAmount: string | number
    paymentDate?: string | null
    status: FinancialTransactionStatus
  }
}

export interface FinancialReconciliation {
  id: string
  tenantId: string
  bankAccountId: string
  reconciliationDate: string
  startDate: string
  endDate: string
  openingBalance: string | number
  closingBalance: string | number
  systemBalance: string | number
  difference: string | number
  status: FinancialReconciliationStatus
  reconciledTransactionsCount: number
  totalIncome: string | number
  totalExpense: string | number
  notes?: string | null
  discrepancyReason?: string | null
  reconciledBy?: string | null
  createdAt: string
  updatedAt: string
  bankAccount?: {
    id: string
    accountName: string
    bankName: string
  }
  items?: FinancialReconciliationItem[]
}

export interface ListTransactionsResponse {
  items: FinancialTransaction[]
  pagination: FinancialPagination
}

export interface ListTransactionsQuery {
  type?: FinancialTransactionType
  status?: FinancialTransactionStatus
  categoryId?: string
  residentId?: string
  residentContractId?: string
  dueDateFrom?: string
  dueDateTo?: string
  search?: string
  sortField?: FinancialTransactionSortField
  sortDirection?: FinancialTransactionSortDirection
  page?: number
  limit?: number
}

export interface ListCategoriesQuery {
  type?: FinancialCategoryType
  search?: string
  activeOnly?: boolean
}

export interface ListBankAccountsQuery {
  accountType?: FinancialAccountType
  search?: string
  activeOnly?: boolean
}

export interface QueryAccountStatementDto {
  fromDate?: string
  toDate?: string
}

export interface ListPaymentMethodsQuery {
  search?: string
  activeOnly?: boolean
}

export interface ListReconciliationsQuery {
  bankAccountId?: string
  status?: FinancialReconciliationStatus
  page?: number
  limit?: number
}

export interface ListUnreconciledPaidTransactionsQuery {
  bankAccountId?: string
  fromDate?: string
  toDate?: string
  search?: string
  page?: number
  limit?: number
}

export interface UnreconciledPaidTransaction {
  id: string
  description: string
  type: FinancialTransactionType
  netAmount: string | number
  paymentDate?: string | null
  status: FinancialTransactionStatus
  category?: {
    id: string
    name: string
    type: FinancialCategoryType
  } | null
  bankAccount?: {
    id: string
    accountName: string
    bankName: string
  } | null
}

export interface ListUnreconciledPaidTransactionsResponse {
  items: UnreconciledPaidTransaction[]
  summary: {
    total: number
    totalIncome: string | number
    totalExpense: string | number
    netImpact: string | number
  }
  pagination: FinancialPagination
}

export interface CreateCategoryDto {
  name: string
  description?: string
  type: FinancialCategoryType
  parentCategoryId?: string
  isActive?: boolean
}

export interface UpdateCategoryDto {
  name?: string
  description?: string
  type?: FinancialCategoryType
  parentCategoryId?: string
  isActive?: boolean
}

export interface CreateTransactionDto {
  type: FinancialTransactionType
  categoryId: string
  residentId?: string
  residentContractId?: string
  amount: string
  discountAmount?: string
  lateFeeAmount?: string
  currency?: string
  issueDate: string
  dueDate: string
  competenceMonth: string
  paymentMethodId?: string
  bankAccountId?: string
  status?: FinancialTransactionStatus
  description: string
  notes?: string
  isAutoGenerated?: boolean
  generationSource?: string
  isRecurring?: boolean
  recurrenceFrequency?: string
}

export interface UpdateTransactionDto extends Partial<CreateTransactionDto> {}

export interface MarkTransactionPaidDto {
  paymentDate: string
}

export interface CreateFinancialAccountDto {
  bankCode: string
  bankName: string
  branch: string
  accountNumber: string
  accountType: FinancialAccountType
  accountName: string
  pixKey?: string
  pixKeyType?: string
  isActive?: boolean
  isDefault?: boolean
  currentBalance?: string
}

export interface UpdateFinancialAccountDto extends Partial<CreateFinancialAccountDto> {}

export interface CreateFinancialPaymentMethodDto {
  name: string
  code: string
  description?: string
  requiresManualConfirmation?: boolean
  allowsInstallments?: boolean
  maxInstallments?: number
  isActive?: boolean
}

export interface UpdateFinancialPaymentMethodDto extends Partial<CreateFinancialPaymentMethodDto> {}

export interface CreateFinancialReconciliationDto {
  bankAccountId: string
  reconciliationDate: string
  startDate: string
  endDate: string
  openingBalance: string
  closingBalance: string
  notes?: string
}

export interface ListReconciliationsResponse {
  items: FinancialReconciliation[]
  pagination: FinancialPagination
}

export interface FinancialAccountStatementEntry {
  id: string
  type: FinancialTransactionType | null
  status: FinancialTransactionStatus | null
  description: string
  paymentDate?: string | null
  netAmount: string | number
  impactAmount: string | number
  runningBalance: string | number
  category: {
    id: string
    name: string
    type: FinancialCategoryType
  } | null
  entryType: string
}

export interface FinancialAccountStatement {
  account: {
    id: string
    accountName: string
    bankName: string
    branch?: string
    accountNumber?: string
    accountType: FinancialAccountType
    currentBalance: string | number
  }
  period: {
    fromDate: string
    toDate: string
  }
  summary: {
    openingBalance: string | number
    closingBalance: string | number
    periodNetImpact: string | number
    entriesCount: number
  }
  entries: FinancialAccountStatementEntry[]
}
