-- AlterEnum: Replace RECORD_VACCINATIONS with CREATE/UPDATE/DELETE_VACCINATIONS
-- This migration updates the PermissionType enum to support granular vaccination permissions

-- Step 1: Create new enum with all values (old + new)
-- We need to recreate the enum because:
-- 1. We're removing RECORD_VACCINATIONS
-- 2. We're adding CREATE/UPDATE/DELETE_VACCINATIONS
-- PostgreSQL doesn't support removing enum values directly

-- Create new enum with updated values
CREATE TYPE "PermissionType_new" AS ENUM (
  'VIEW_RESIDENTS',
  'CREATE_RESIDENTS',
  'UPDATE_RESIDENTS',
  'DELETE_RESIDENTS',
  'VIEW_DAILY_RECORDS',
  'CREATE_DAILY_RECORDS',
  'UPDATE_DAILY_RECORDS',
  'DELETE_DAILY_RECORDS',
  'VIEW_PRESCRIPTIONS',
  'CREATE_PRESCRIPTIONS',
  'UPDATE_PRESCRIPTIONS',
  'DELETE_PRESCRIPTIONS',
  'VIEW_MEDICATIONS',
  'ADMINISTER_MEDICATIONS',
  'ADMINISTER_CONTROLLED_MEDICATIONS',
  'VIEW_VITAL_SIGNS',
  'RECORD_VITAL_SIGNS',
  'VIEW_VACCINATIONS',
  'CREATE_VACCINATIONS',
  'UPDATE_VACCINATIONS',
  'DELETE_VACCINATIONS',
  'VIEW_CLINICAL_NOTES',
  'CREATE_CLINICAL_NOTES',
  'UPDATE_CLINICAL_NOTES',
  'DELETE_CLINICAL_NOTES',
  'VIEW_CLINICAL_PROFILE',
  'UPDATE_CLINICAL_PROFILE',
  'VIEW_ALLERGIES',
  'CREATE_ALLERGIES',
  'UPDATE_ALLERGIES',
  'DELETE_ALLERGIES',
  'VIEW_CONDITIONS',
  'CREATE_CONDITIONS',
  'UPDATE_CONDITIONS',
  'DELETE_CONDITIONS',
  'VIEW_DIETARY_RESTRICTIONS',
  'CREATE_DIETARY_RESTRICTIONS',
  'UPDATE_DIETARY_RESTRICTIONS',
  'DELETE_DIETARY_RESTRICTIONS',
  'VIEW_BEDS',
  'MANAGE_BEDS',
  'MANAGE_INFRASTRUCTURE',
  'VIEW_DOCUMENTS',
  'UPLOAD_DOCUMENTS',
  'DELETE_DOCUMENTS',
  'VIEW_USERS',
  'CREATE_USERS',
  'UPDATE_USERS',
  'DELETE_USERS',
  'MANAGE_PERMISSIONS',
  'VIEW_REPORTS',
  'EXPORT_DATA',
  'VIEW_AUDIT_LOGS',
  'VIEW_INSTITUTIONAL_SETTINGS',
  'UPDATE_INSTITUTIONAL_SETTINGS',
  'VIEW_INSTITUTIONAL_PROFILE',
  'UPDATE_INSTITUTIONAL_PROFILE',
  'VIEW_POPS',
  'CREATE_POPS',
  'UPDATE_POPS',
  'DELETE_POPS',
  'PUBLISH_POPS',
  'MANAGE_POPS',
  'VIEW_RESIDENT_SCHEDULE',
  'MANAGE_RESIDENT_SCHEDULE'
);

-- Update user_permissions table to use new enum
ALTER TABLE "user_permissions"
  ALTER COLUMN "permission" TYPE "PermissionType_new"
  USING ("permission"::text::"PermissionType_new");

-- Drop old enum and rename new one
DROP TYPE "PermissionType";
ALTER TYPE "PermissionType_new" RENAME TO "PermissionType";
