-- Idempotência de geração automática de mensalidades por contrato/competência
-- Mantém apenas o primeiro registro ativo quando houver duplicidade histórica.
WITH duplicated_rows AS (
  SELECT
    id,
    ROW_NUMBER() OVER (
      PARTITION BY "residentContractId", "competenceMonth", "generationSource"
      ORDER BY "createdAt" ASC
    ) AS rn
  FROM "financial_transactions"
  WHERE "deletedAt" IS NULL
    AND "residentContractId" IS NOT NULL
    AND "isAutoGenerated" = true
    AND "generationSource" = 'RESIDENT_CONTRACT'
)
UPDATE "financial_transactions" t
SET "deletedAt" = now()
FROM duplicated_rows d
WHERE t.id = d.id
  AND d.rn > 1;

CREATE UNIQUE INDEX IF NOT EXISTS "financial_transactions_contract_competence_unique"
  ON "financial_transactions" ("residentContractId", "competenceMonth", "generationSource")
  WHERE "deletedAt" IS NULL
    AND "residentContractId" IS NOT NULL
    AND "generationSource" = 'RESIDENT_CONTRACT';
