-- AlterEnum: Adicionar novas permissões para dados clínicos
ALTER TYPE "PermissionType" ADD VALUE 'VIEW_CLINICAL_PROFILE';
ALTER TYPE "PermissionType" ADD VALUE 'UPDATE_CLINICAL_PROFILE';
ALTER TYPE "PermissionType" ADD VALUE 'VIEW_ALLERGIES';
ALTER TYPE "PermissionType" ADD VALUE 'CREATE_ALLERGIES';
ALTER TYPE "PermissionType" ADD VALUE 'UPDATE_ALLERGIES';
ALTER TYPE "PermissionType" ADD VALUE 'DELETE_ALLERGIES';
ALTER TYPE "PermissionType" ADD VALUE 'VIEW_CONDITIONS';
ALTER TYPE "PermissionType" ADD VALUE 'CREATE_CONDITIONS';
ALTER TYPE "PermissionType" ADD VALUE 'UPDATE_CONDITIONS';
ALTER TYPE "PermissionType" ADD VALUE 'DELETE_CONDITIONS';
ALTER TYPE "PermissionType" ADD VALUE 'VIEW_DIETARY_RESTRICTIONS';
ALTER TYPE "PermissionType" ADD VALUE 'CREATE_DIETARY_RESTRICTIONS';
ALTER TYPE "PermissionType" ADD VALUE 'UPDATE_DIETARY_RESTRICTIONS';
ALTER TYPE "PermissionType" ADD VALUE 'DELETE_DIETARY_RESTRICTIONS';
