import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  FinancialTransactionStatus,
  FinancialTransactionType,
} from '@prisma/client';
import {
  IsEnum,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  MinLength,
} from 'class-validator';
import { IsDateOnly } from '../../common/validators/date.validators';

export class CreateTransactionDto {
  @ApiProperty({ enum: FinancialTransactionType, example: FinancialTransactionType.INCOME })
  @IsEnum(FinancialTransactionType)
  type: FinancialTransactionType;

  @ApiProperty({ description: 'ID da categoria' })
  @IsUUID()
  categoryId: string;

  @ApiPropertyOptional({ description: 'ID do residente (opcional)' })
  @IsOptional()
  @IsUUID()
  residentId?: string;

  @ApiPropertyOptional({ description: 'ID do contrato do residente (opcional)' })
  @IsOptional()
  @IsUUID()
  residentContractId?: string;

  @ApiProperty({ example: '1500.00', description: 'Valor bruto' })
  @IsString()
  amount: string;

  @ApiPropertyOptional({ example: '0.00' })
  @IsOptional()
  @IsString()
  discountAmount?: string;

  @ApiPropertyOptional({ example: '0.00' })
  @IsOptional()
  @IsString()
  lateFeeAmount?: string;

  @ApiPropertyOptional({ default: 'BRL' })
  @IsOptional()
  @IsString()
  @MaxLength(3)
  currency?: string;

  @ApiProperty({ example: '2026-02-12' })
  @IsDateOnly()
  issueDate: string;

  @ApiProperty({ example: '2026-02-20' })
  @IsDateOnly()
  dueDate: string;

  @ApiProperty({ example: '2026-02-01', description: 'Primeiro dia do mês de competência' })
  @IsDateOnly()
  competenceMonth: string;

  @ApiPropertyOptional({ description: 'ID do método de pagamento' })
  @IsOptional()
  @IsUUID()
  paymentMethodId?: string;

  @ApiPropertyOptional({ description: 'ID da conta bancária' })
  @IsOptional()
  @IsUUID()
  bankAccountId?: string;

  @ApiPropertyOptional({ enum: FinancialTransactionStatus, default: FinancialTransactionStatus.PENDING })
  @IsOptional()
  @IsEnum(FinancialTransactionStatus)
  status?: FinancialTransactionStatus;

  @ApiProperty({ example: 'Mensalidade fevereiro/2026' })
  @IsString()
  @MinLength(3)
  description: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  notes?: string;

  @ApiPropertyOptional({ default: false })
  @IsOptional()
  isAutoGenerated?: boolean;

  @ApiPropertyOptional({ example: 'monthly_contract' })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  generationSource?: string;

  @ApiPropertyOptional({ default: false })
  @IsOptional()
  isRecurring?: boolean;

  @ApiPropertyOptional({ example: 'monthly' })
  @IsOptional()
  @IsString()
  @MaxLength(20)
  recurrenceFrequency?: string;
}
