-- AlterEnum: Add institutional events permissions to PermissionType
ALTER TYPE "PermissionType" ADD VALUE 'VIEW_INSTITUTIONAL_EVENTS';
ALTER TYPE "PermissionType" ADD VALUE 'CREATE_INSTITUTIONAL_EVENTS';
ALTER TYPE "PermissionType" ADD VALUE 'UPDATE_INSTITUTIONAL_EVENTS';
ALTER TYPE "PermissionType" ADD VALUE 'DELETE_INSTITUTIONAL_EVENTS';
