-- CreateEnum
ALTER TYPE "AlertType" ADD VALUE 'PLAN_CHANGED';
ALTER TYPE "AlertType" ADD VALUE 'PERIOD_EXTENDED';
ALTER TYPE "AlertType" ADD VALUE 'SUBSCRIPTION_REACTIVATED';
ALTER TYPE "AlertType" ADD VALUE 'DISCOUNT_APPLIED';
ALTER TYPE "AlertType" ADD VALUE 'CUSTOM_PRICE_APPLIED';
ALTER TYPE "AlertType" ADD VALUE 'DISCOUNT_REMOVED';
ALTER TYPE "AlertType" ADD VALUE 'TRIAL_CONVERTED';
