-- Financial Operations MVP (tenant-scoped)
-- NOTE: This migration intentionally does not touch SaaS billing tables.

-- 1) Extend PermissionType enum
ALTER TYPE "PermissionType" ADD VALUE IF NOT EXISTS 'VIEW_FINANCIAL_OPERATIONS';
ALTER TYPE "PermissionType" ADD VALUE IF NOT EXISTS 'MANAGE_FINANCIAL_CATEGORIES';
ALTER TYPE "PermissionType" ADD VALUE IF NOT EXISTS 'MANAGE_FINANCIAL_TRANSACTIONS';
ALTER TYPE "PermissionType" ADD VALUE IF NOT EXISTS 'MANAGE_FINANCIAL_ACCOUNTS';
ALTER TYPE "PermissionType" ADD VALUE IF NOT EXISTS 'MANAGE_FINANCIAL_RECONCILIATION';
ALTER TYPE "PermissionType" ADD VALUE IF NOT EXISTS 'VIEW_FINANCIAL_DASHBOARD';

-- 2) Create financial enums if needed
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'FinancialCategoryType') THEN
    CREATE TYPE "FinancialCategoryType" AS ENUM ('INCOME', 'EXPENSE');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'FinancialAccountType') THEN
    CREATE TYPE "FinancialAccountType" AS ENUM ('CHECKING', 'SAVINGS', 'PAYMENT');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'FinancialTransactionType') THEN
    CREATE TYPE "FinancialTransactionType" AS ENUM ('INCOME', 'EXPENSE');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'FinancialTransactionStatus') THEN
    CREATE TYPE "FinancialTransactionStatus" AS ENUM (
      'PENDING',
      'PAID',
      'OVERDUE',
      'CANCELLED',
      'REFUNDED',
      'PARTIALLY_PAID'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'FinancialReconciliationStatus') THEN
    CREATE TYPE "FinancialReconciliationStatus" AS ENUM (
      'PENDING',
      'IN_PROGRESS',
      'RECONCILED',
      'DISCREPANCY'
    );
  END IF;
END $$;

-- 3) Core tables
CREATE TABLE IF NOT EXISTS "financial_categories" (
  "id" UUID NOT NULL,
  "tenantId" UUID NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "description" TEXT,
  "type" "FinancialCategoryType" NOT NULL,
  "parentCategoryId" UUID,
  "isSystemDefault" BOOLEAN NOT NULL DEFAULT false,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdBy" UUID NOT NULL,
  "updatedBy" UUID,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deletedAt" TIMESTAMPTZ(3),
  CONSTRAINT "financial_categories_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "financial_payment_methods" (
  "id" UUID NOT NULL,
  "tenantId" UUID NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "code" VARCHAR(50) NOT NULL,
  "description" TEXT,
  "requiresManualConfirmation" BOOLEAN NOT NULL DEFAULT false,
  "allowsInstallments" BOOLEAN NOT NULL DEFAULT false,
  "maxInstallments" INTEGER NOT NULL DEFAULT 1,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deletedAt" TIMESTAMPTZ(3),
  CONSTRAINT "financial_payment_methods_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "financial_bank_accounts" (
  "id" UUID NOT NULL,
  "tenantId" UUID NOT NULL,
  "bankCode" VARCHAR(10) NOT NULL,
  "bankName" VARCHAR(100) NOT NULL,
  "branch" VARCHAR(20) NOT NULL,
  "accountNumber" VARCHAR(50) NOT NULL,
  "accountType" "FinancialAccountType" NOT NULL,
  "pixKey" VARCHAR(100),
  "pixKeyType" VARCHAR(20),
  "accountName" VARCHAR(100) NOT NULL,
  "currentBalance" DECIMAL(15,2) NOT NULL DEFAULT 0,
  "lastBalanceUpdate" TIMESTAMPTZ(3),
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "isDefault" BOOLEAN NOT NULL DEFAULT false,
  "createdBy" UUID NOT NULL,
  "updatedBy" UUID,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deletedAt" TIMESTAMPTZ(3),
  CONSTRAINT "financial_bank_accounts_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "financial_transactions" (
  "id" UUID NOT NULL,
  "tenantId" UUID NOT NULL,
  "transactionNumber" VARCHAR(50),
  "type" "FinancialTransactionType" NOT NULL,
  "categoryId" UUID NOT NULL,
  "residentId" UUID,
  "residentContractId" UUID,
  "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
  "generationSource" VARCHAR(50),
  "amount" DECIMAL(15,2) NOT NULL,
  "currency" VARCHAR(3) NOT NULL DEFAULT 'BRL',
  "discountAmount" DECIMAL(15,2) NOT NULL DEFAULT 0,
  "lateFeeAmount" DECIMAL(15,2) NOT NULL DEFAULT 0,
  "netAmount" DECIMAL(15,2) NOT NULL,
  "issueDate" DATE NOT NULL,
  "dueDate" DATE NOT NULL,
  "paymentDate" DATE,
  "competenceMonth" DATE NOT NULL,
  "paymentMethodId" UUID,
  "bankAccountId" UUID,
  "status" "FinancialTransactionStatus" NOT NULL DEFAULT 'PENDING',
  "description" TEXT NOT NULL,
  "notes" TEXT,
  "isRecurring" BOOLEAN NOT NULL DEFAULT false,
  "recurrenceId" UUID,
  "recurrenceFrequency" VARCHAR(20),
  "attachmentDocumentId" UUID,
  "createdBy" UUID NOT NULL,
  "confirmedBy" UUID,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deletedAt" TIMESTAMPTZ(3),
  CONSTRAINT "financial_transactions_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "financial_reconciliations" (
  "id" UUID NOT NULL,
  "tenantId" UUID NOT NULL,
  "bankAccountId" UUID NOT NULL,
  "reconciliationDate" DATE NOT NULL,
  "startDate" DATE NOT NULL,
  "endDate" DATE NOT NULL,
  "openingBalance" DECIMAL(15,2) NOT NULL,
  "closingBalance" DECIMAL(15,2) NOT NULL,
  "systemBalance" DECIMAL(15,2) NOT NULL,
  "difference" DECIMAL(15,2) NOT NULL,
  "status" "FinancialReconciliationStatus" NOT NULL DEFAULT 'PENDING',
  "reconciledTransactionsCount" INTEGER NOT NULL DEFAULT 0,
  "totalIncome" DECIMAL(15,2) NOT NULL DEFAULT 0,
  "totalExpense" DECIMAL(15,2) NOT NULL DEFAULT 0,
  "notes" TEXT,
  "discrepancyReason" TEXT,
  "reconciledBy" UUID,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "financial_reconciliations_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "financial_reconciliation_items" (
  "id" UUID NOT NULL,
  "reconciliationId" UUID NOT NULL,
  "transactionId" UUID NOT NULL,
  "isReconciled" BOOLEAN NOT NULL DEFAULT false,
  "reconciliationNotes" TEXT,
  "reconciledAt" TIMESTAMPTZ(3),
  "reconciledBy" UUID,
  CONSTRAINT "financial_reconciliation_items_pkey" PRIMARY KEY ("id")
);

-- 4) Unique constraints
CREATE UNIQUE INDEX IF NOT EXISTS "financial_categories_tenant_name_deletedAt_key"
  ON "financial_categories" ("tenantId", "name", "deletedAt");

CREATE UNIQUE INDEX IF NOT EXISTS "financial_payment_methods_tenant_code_deletedAt_key"
  ON "financial_payment_methods" ("tenantId", "code", "deletedAt");

CREATE UNIQUE INDEX IF NOT EXISTS "financial_bank_accounts_tenant_bank_branch_number_deletedAt_key"
  ON "financial_bank_accounts" ("tenantId", "bankCode", "branch", "accountNumber", "deletedAt");

CREATE UNIQUE INDEX IF NOT EXISTS "financial_reconciliations_tenant_bankAccount_reconciliationDate_key"
  ON "financial_reconciliations" ("tenantId", "bankAccountId", "reconciliationDate");

CREATE UNIQUE INDEX IF NOT EXISTS "financial_reconciliation_items_reconciliation_transaction_key"
  ON "financial_reconciliation_items" ("reconciliationId", "transactionId");

-- 5) Performance indexes
CREATE INDEX IF NOT EXISTS "financial_categories_tenant_type_isActive_idx"
  ON "financial_categories" ("tenantId", "type", "isActive");
CREATE INDEX IF NOT EXISTS "financial_categories_tenant_parent_idx"
  ON "financial_categories" ("tenantId", "parentCategoryId");
CREATE INDEX IF NOT EXISTS "financial_categories_deletedAt_idx"
  ON "financial_categories" ("deletedAt");

CREATE INDEX IF NOT EXISTS "financial_payment_methods_tenant_isActive_idx"
  ON "financial_payment_methods" ("tenantId", "isActive");
CREATE INDEX IF NOT EXISTS "financial_payment_methods_deletedAt_idx"
  ON "financial_payment_methods" ("deletedAt");

CREATE INDEX IF NOT EXISTS "financial_bank_accounts_tenant_isActive_idx"
  ON "financial_bank_accounts" ("tenantId", "isActive");
CREATE INDEX IF NOT EXISTS "financial_bank_accounts_tenant_isDefault_idx"
  ON "financial_bank_accounts" ("tenantId", "isDefault");
CREATE INDEX IF NOT EXISTS "financial_bank_accounts_deletedAt_idx"
  ON "financial_bank_accounts" ("deletedAt");

CREATE INDEX IF NOT EXISTS "financial_transactions_tenant_status_dueDate_idx"
  ON "financial_transactions" ("tenantId", "status", "dueDate");
CREATE INDEX IF NOT EXISTS "financial_transactions_tenant_competence_type_idx"
  ON "financial_transactions" ("tenantId", "competenceMonth", "type");
CREATE INDEX IF NOT EXISTS "financial_transactions_tenant_resident_idx"
  ON "financial_transactions" ("tenantId", "residentId");
CREATE INDEX IF NOT EXISTS "financial_transactions_tenant_residentContract_idx"
  ON "financial_transactions" ("tenantId", "residentContractId");
CREATE INDEX IF NOT EXISTS "financial_transactions_category_idx"
  ON "financial_transactions" ("categoryId");
CREATE INDEX IF NOT EXISTS "financial_transactions_paymentMethod_idx"
  ON "financial_transactions" ("paymentMethodId");
CREATE INDEX IF NOT EXISTS "financial_transactions_bankAccount_idx"
  ON "financial_transactions" ("bankAccountId");
CREATE INDEX IF NOT EXISTS "financial_transactions_deletedAt_idx"
  ON "financial_transactions" ("deletedAt");

CREATE INDEX IF NOT EXISTS "financial_reconciliations_tenant_bank_status_idx"
  ON "financial_reconciliations" ("tenantId", "bankAccountId", "status");

CREATE INDEX IF NOT EXISTS "financial_reconciliation_items_transaction_idx"
  ON "financial_reconciliation_items" ("transactionId");

-- 6) Foreign keys
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'financial_categories_parentCategoryId_fkey'
  ) THEN
    ALTER TABLE "financial_categories"
      ADD CONSTRAINT "financial_categories_parentCategoryId_fkey"
      FOREIGN KEY ("parentCategoryId") REFERENCES "financial_categories"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'financial_transactions_categoryId_fkey'
  ) THEN
    ALTER TABLE "financial_transactions"
      ADD CONSTRAINT "financial_transactions_categoryId_fkey"
      FOREIGN KEY ("categoryId") REFERENCES "financial_categories"("id")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'financial_transactions_paymentMethodId_fkey'
  ) THEN
    ALTER TABLE "financial_transactions"
      ADD CONSTRAINT "financial_transactions_paymentMethodId_fkey"
      FOREIGN KEY ("paymentMethodId") REFERENCES "financial_payment_methods"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'financial_transactions_bankAccountId_fkey'
  ) THEN
    ALTER TABLE "financial_transactions"
      ADD CONSTRAINT "financial_transactions_bankAccountId_fkey"
      FOREIGN KEY ("bankAccountId") REFERENCES "financial_bank_accounts"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'financial_transactions_residentId_fkey'
  ) THEN
    ALTER TABLE "financial_transactions"
      ADD CONSTRAINT "financial_transactions_residentId_fkey"
      FOREIGN KEY ("residentId") REFERENCES "residents"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'financial_transactions_residentContractId_fkey'
  ) THEN
    ALTER TABLE "financial_transactions"
      ADD CONSTRAINT "financial_transactions_residentContractId_fkey"
      FOREIGN KEY ("residentContractId") REFERENCES "resident_contracts"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'financial_reconciliations_bankAccountId_fkey'
  ) THEN
    ALTER TABLE "financial_reconciliations"
      ADD CONSTRAINT "financial_reconciliations_bankAccountId_fkey"
      FOREIGN KEY ("bankAccountId") REFERENCES "financial_bank_accounts"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'financial_reconciliation_items_reconciliationId_fkey'
  ) THEN
    ALTER TABLE "financial_reconciliation_items"
      ADD CONSTRAINT "financial_reconciliation_items_reconciliationId_fkey"
      FOREIGN KEY ("reconciliationId") REFERENCES "financial_reconciliations"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'financial_reconciliation_items_transactionId_fkey'
  ) THEN
    ALTER TABLE "financial_reconciliation_items"
      ADD CONSTRAINT "financial_reconciliation_items_transactionId_fkey"
      FOREIGN KEY ("transactionId") REFERENCES "financial_transactions"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
